services:
  - type: web
    name: ocr-pdf
    env: python
    plan: free
    buildCommand: |
      apt-get update
      apt-get install -y \
        tesseract-ocr \
        tesseract-ocr-spa \
        tesseract-ocr-eng \
        ghostscript \
        qpdf \
        poppler-utils \
        unpaper
      pip install -r requirements.txt
    startCommand: gunicorn app:app
